REM remove destination folders first
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie1"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie2"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie3"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie4"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie6"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie7"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie8"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie9"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie10"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie11"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie12"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie13"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie14"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie15"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie16"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie17"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie18"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie19"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie20"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie21"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie22"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie23"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie24"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie25"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie26"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie27"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie28"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie29"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie30"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie31"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie32"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie33"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie34"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie35"

REM recreate empty destination folders
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie1"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie2"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie3"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie4"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie6"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie7"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie8"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie9"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie10"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie11"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie12"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie13"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie14"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie15"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie16"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie17"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie18"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie19"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie20"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie21"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie22"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie23"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie24"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie25"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie26"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie27"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie28"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie29"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie30"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie31"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie32"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie33"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie34"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie35"

REM strat1
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie1/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie1/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie1/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie1/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie1/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie1/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie1/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie1/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie1/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie1/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie1/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie1/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie1/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie1/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie1/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie1/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie1/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie1/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie1/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie1/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie1/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie1/"

REM strat2
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie2/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie2/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie2/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie2/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie2/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie2/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie2/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie2/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie2/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie2/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie2/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie2/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie2/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie2/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie2/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie2/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie2/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie2/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie2/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie2/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie2/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie2/"

REM strat3
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie3/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie3/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie3/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie3/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie3/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie3/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie3/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie3/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie3/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie3/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie3/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie3/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie3/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie3/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie3/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie3/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie3/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie3/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie3/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie3/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie3/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie3/"

REM strat4
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie4/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie4/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie4/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie4/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie4/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie4/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie4/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie4/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie4/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie4/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie4/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie4/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie4/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie4/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie4/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie4/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie4/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie4/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie4/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie4/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie4/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie4/"

REM ref19
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie6/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie6/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie6/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie6/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie6/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie6/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie6/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie6/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie6/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie6/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie6/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie6/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie6/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie6/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie6/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie6/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie6/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie6/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie6/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie6/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie6/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie6/"

REM ref30
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie7/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie7/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie7/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie7/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie7/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie7/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie7/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie7/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie7/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie7/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie7/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie7/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie7/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie7/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie7/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie7/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie7/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie7/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie7/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie7/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie7/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie7/"

REM LN
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie8/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie8/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie8/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie8/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie8/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie8/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie8/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie8/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie8/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie8/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie8/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie8/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie8/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie8/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie8/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie8/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie8/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie8/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie8/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie8/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie8/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie8/"

REM LNGA01
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie9/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie9/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie9/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie9/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie9/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie9/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie9/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie9/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie9/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie9/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie9/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie9/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie9/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie9/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie9/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie9/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie9/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie9/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie9/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie9/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie9/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie9/"

REM LNGA02
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie10/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie10/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie10/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie10/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie10/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie10/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie10/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie10/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie10/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie10/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie10/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie10/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie10/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie10/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie10/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie10/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie10/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie10/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie10/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie10/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie10/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie10/"

REM S1GA03
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie11/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie11/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie11/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie11/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie11/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie11/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie11/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie11/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie11/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie11/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie11/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie11/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie11/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie11/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie11/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie11/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie11/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie11/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie11/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie11/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie11/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie11/"

REM S2GA03
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie12/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie12/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie12/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie12/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie12/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie12/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie12/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie12/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie12/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie12/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie12/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie12/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie12/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie12/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie12/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie12/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie12/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie12/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie12/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie12/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie12/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie12/"

REM S3GA03
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie13/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie13/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie13/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie13/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie13/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie13/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie13/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie13/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie13/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie13/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie13/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie13/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie13/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie13/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie13/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie13/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie13/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie13/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie13/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie13/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie13/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie13/"

REM S4GA03
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie14/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie14/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie14/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie14/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie14/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie14/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie14/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie14/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie14/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie14/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie14/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie14/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie14/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie14/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie14/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie14/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie14/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie14/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie14/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie14/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie14/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie14/"

REM LNGA03
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie15/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie15/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie15/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie15/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie15/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie15/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie15/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie15/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie15/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie15/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie15/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie15/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie15/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie15/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie15/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie15/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie15/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie15/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie15/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie15/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie15/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie15/"

REM S1GA04
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie16/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie16/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie16/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie16/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie16/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie16/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie16/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie16/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie16/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie16/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie16/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie16/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie16/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie16/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie16/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie16/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie16/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie16/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie16/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie16/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie16/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie16/"

REM S2GA04
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie17/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie17/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie17/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie17/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie17/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie17/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie17/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie17/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie17/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie17/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie17/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie17/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie17/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie17/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie17/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie17/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie17/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie17/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie17/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie17/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie17/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie17/"

REM S3GA04
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie18/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie18/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie18/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie18/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie18/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie18/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie18/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie18/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie18/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie18/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie18/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie18/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie18/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie18/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie18/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie18/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie18/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie18/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie18/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie18/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie18/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie18/"

REM S4GA04
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie19/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie19/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie19/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie19/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie19/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie19/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie19/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie19/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie19/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie19/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie19/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie19/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie19/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie19/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie19/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie19/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie19/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie19/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie19/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie19/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie19/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie19/"

REM LNGA04
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie20/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie20/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie20/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie20/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie20/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie20/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie20/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie20/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie20/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie20/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie20/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie20/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie20/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie20/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie20/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie20/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie20/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie20/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie20/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie20/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie20/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie20/"

REM S1GA05
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie21/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie21/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie21/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie21/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie21/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie21/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie21/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie21/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie21/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie21/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie21/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie21/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie21/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie21/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie21/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie21/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie21/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie21/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie21/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie21/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie21/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie21/"

REM S2GA05
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie22/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie22/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie22/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie22/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie22/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie22/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie22/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie22/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie22/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie22/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie22/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie22/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie22/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie22/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie22/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie22/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie22/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie22/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie22/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie22/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie22/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie22/"

REM S3GA05
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie23/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie23/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie23/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie23/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie23/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie23/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie23/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie23/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie23/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie23/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie23/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie23/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie23/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie23/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie23/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie23/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie23/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie23/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie23/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie23/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie23/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie23/"

REM S4GA05
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie24/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie24/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie24/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie24/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie24/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie24/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie24/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie24/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie24/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie24/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie24/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie24/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie24/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie24/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie24/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie24/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie24/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie24/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie24/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie24/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie24/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie24/"

REM LNGA05
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie25/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie25/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie25/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie25/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie25/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie25/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie25/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie25/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie25/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie25/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie25/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie25/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie25/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie25/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie25/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie25/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie25/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie25/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie25/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie25/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie25/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie25/"

REM S1GA06
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie26/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie26/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie26/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie26/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie26/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie26/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie26/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie26/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie26/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie26/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie26/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie26/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie26/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie26/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie26/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie26/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie26/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie26/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie26/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie26/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie26/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie26/"

REM S2GA06
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie27/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie27/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie27/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie27/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie27/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie27/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie27/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie27/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie27/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie27/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie27/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie27/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie27/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie27/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie27/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie27/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie27/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie27/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie27/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie27/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie27/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie27/"

REM S3GA06
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie28/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie28/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie28/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie28/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie28/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie28/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie28/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie28/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie28/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie28/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie28/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie28/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie28/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie28/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie28/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie28/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie28/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie28/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie28/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie28/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie28/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie28/"

REM S4GA06
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie29/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie29/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie29/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie29/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie29/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie29/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie29/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie29/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie29/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie29/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie29/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie29/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie29/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie29/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie29/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie29/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie29/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie29/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie29/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie29/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie29/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie29/"

REM LNGA06
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie30/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie30/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie30/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie30/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie30/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie30/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie30/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie30/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie30/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie30/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie30/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie30/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie30/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie30/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie30/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie30/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie30/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie30/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie30/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie30/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie30/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie30/"

REM S1GA07
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie31/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie31/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie31/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie31/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie31/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie31/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie31/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie31/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie31/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie31/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie31/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie31/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie31/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie31/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie31/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie31/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie31/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie31/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie31/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie31/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie31/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie31/"

REM S2GA07
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie32/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie32/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie32/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie32/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie32/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie32/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie32/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie32/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie32/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie32/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie32/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie32/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie32/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie32/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie32/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie32/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie32/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie32/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie32/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie32/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie32/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie32/"

REM S3GA07
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie33/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie33/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie33/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie33/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie33/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie33/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie33/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie33/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie33/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie33/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie33/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie33/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie33/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie33/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie33/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie33/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie33/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie33/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie33/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie33/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie33/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie33/"

REM S4GA07
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie34/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie34/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie34/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie34/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie34/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie34/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie34/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie34/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie34/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie34/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie34/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie34/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie34/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie34/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie34/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie34/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie34/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie34/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie34/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie34/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie34/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie34/"

REM LNGA07
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie35/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie35/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie35/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie35/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie35/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie35/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie35/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie35/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie35/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie35/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie35/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie35/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie35/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie35/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie35/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie35/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie35/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie35/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie35/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie35/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie35/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie35/"