REM remove destination folders first
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie1"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie2"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie3"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie4"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie6"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie7"
rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie8"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie9"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie10"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie11"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie12"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie13"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie14"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie15"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie16"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie17"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie18"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie19"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie20"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie21"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie22"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie23"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie24"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie25"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie26"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie27"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie28"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie29"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie30"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie31"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie32"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie33"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie34"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie35"
REM rmdir /s /q "E:/LocalData/startanalyse_tiles/tiles/Strategie36"

REM REM recreate empty destination folders
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie1"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie2"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie3"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie4"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie6"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie7"
mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie8"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie9"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie10"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie11"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie12"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie13"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie14"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie15"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie16"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie17"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie18"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie19"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie20"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie21"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie22"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie23"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie24"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie25"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie26"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie27"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie28"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie29"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie30"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie31"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie32"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie33"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie34"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie35"
REM mkdir "E:/LocalData/startanalyse_tiles/tiles/Strategie36"

REM REM strat1
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie1/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie1/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie1/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie1/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie1/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie1/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie1/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie1/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie1/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie1/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie1/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie1/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie1/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie1/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie1/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie1/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie1/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie1/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie1/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie1/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie1/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie1/"

REM REM strat2
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie2/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie2/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie2/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie2/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie2/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie2/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie2/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie2/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie2/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie2/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie2/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie2/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie2/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie2/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie2/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie2/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie2/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie2/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie2/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie2/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie2/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie2/"

REM REM strat3
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie3/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie3/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie3/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie3/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie3/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie3/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie3/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie3/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie3/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie3/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie3/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie3/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie3/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie3/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie3/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie3/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie3/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie3/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie3/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie3/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie3/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie3/"

REM REM strat4
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie4/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie4/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie4/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie4/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie4/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie4/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie4/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie4/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie4/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie4/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie4/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie4/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie4/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie4/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie4/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie4/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie4/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie4/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie4/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie4/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie4/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie4/"

REM REM ref19
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie6/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie6/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie6/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie6/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie6/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie6/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie6/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie6/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie6/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie6/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie6/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie6/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie6/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie6/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie6/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie6/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie6/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie6/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie6/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie6/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie6/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie6/"

REM REM ref30
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie7/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie7/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie7/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie7/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie7/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie7/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie7/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie7/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie7/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie7/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie7/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie7/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie7/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie7/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie7/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie7/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie7/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie7/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie7/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie7/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie7/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie7/"

REM LN
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie8/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie8/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie8/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie8/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie8/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie8/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie8/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie8/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie8/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie8/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie8/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie8/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie8/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie8/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie8/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie8/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie8/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie8/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie8/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie8/"
move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie8/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie8/"

REM LNGA01
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie9/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie9/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie9/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie9/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie9/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie9/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie9/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie9/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie9/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie9/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie9/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie9/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie9/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie9/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie9/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie9/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie9/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie9/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie9/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie9/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie9/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie9/"

REM REM LNGA02
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie10/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie10/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie10/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie10/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie10/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie10/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie10/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie10/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie10/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie10/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie10/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie10/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie10/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie10/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie10/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie10/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie10/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie10/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie10/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie10/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie10/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie10/"

REM REM S1GA03
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie11/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie11/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie11/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie11/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie11/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie11/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie11/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie11/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie11/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie11/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie11/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie11/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie11/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie11/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie11/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie11/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie11/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie11/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie11/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie11/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie11/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie11/"

REM REM S2GA03
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie12/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie12/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie12/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie12/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie12/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie12/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie12/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie12/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie12/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie12/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie12/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie12/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie12/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie12/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie12/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie12/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie12/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie12/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie12/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie12/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie12/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie12/"

REM REM S3GA03
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie13/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie13/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie13/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie13/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie13/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie13/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie13/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie13/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie13/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie13/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie13/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie13/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie13/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie13/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie13/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie13/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie13/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie13/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie13/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie13/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie13/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie13/"

REM REM S4GA03
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie14/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie14/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie14/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie14/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie14/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie14/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie14/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie14/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie14/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie14/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie14/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie14/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie14/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie14/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie14/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie14/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie14/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie14/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie14/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie14/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie14/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie14/"

REM REM LNGA03
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie15/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie15/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie15/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie15/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie15/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie15/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie15/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie15/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie15/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie15/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie15/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie15/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie15/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie15/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie15/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie15/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie15/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie15/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie15/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie15/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie15/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie15/"

REM REM S1GA04
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie16/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie16/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie16/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie16/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie16/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie16/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie16/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie16/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie16/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie16/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie16/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie16/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie16/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie16/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie16/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie16/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie16/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie16/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie16/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie16/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie16/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie16/"

REM REM S2GA04
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie17/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie17/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie17/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie17/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie17/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie17/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie17/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie17/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie17/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie17/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie17/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie17/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie17/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie17/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie17/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie17/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie17/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie17/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie17/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie17/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie17/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie17/"

REM REM S3GA04
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie18/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie18/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie18/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie18/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie18/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie18/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie18/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie18/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie18/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie18/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie18/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie18/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie18/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie18/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie18/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie18/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie18/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie18/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie18/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie18/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie18/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie18/"

REM REM S4GA04
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie19/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie19/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie19/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie19/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie19/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie19/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie19/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie19/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie19/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie19/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie19/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie19/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie19/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie19/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie19/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie19/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie19/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie19/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie19/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie19/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie19/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie19/"

REM REM LNGA04
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie20/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie20/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie20/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie20/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie20/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie20/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie20/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie20/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie20/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie20/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie20/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie20/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie20/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie20/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie20/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie20/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie20/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie20/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie20/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie20/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie20/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie20/"

REM REM S1GA05
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie21/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie21/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie21/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie21/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie21/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie21/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie21/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie21/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie21/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie21/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie21/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie21/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie21/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie21/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie21/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie21/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie21/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie21/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie21/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie21/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie21/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie21/"

REM REM S2GA05
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie22/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie22/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie22/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie22/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie22/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie22/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie22/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie22/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie22/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie22/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie22/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie22/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie22/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie22/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie22/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie22/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie22/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie22/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie22/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie22/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie22/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie22/"

REM REM S3GA05
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie23/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie23/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie23/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie23/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie23/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie23/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie23/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie23/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie23/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie23/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie23/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie23/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie23/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie23/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie23/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie23/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie23/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie23/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie23/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie23/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie23/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie23/"

REM REM S4GA05
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie24/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie24/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie24/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie24/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie24/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie24/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie24/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie24/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie24/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie24/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie24/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie24/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie24/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie24/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie24/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie24/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie24/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie24/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie24/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie24/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie24/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie24/"

REM REM LNGA05
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie25/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie25/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie25/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie25/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie25/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie25/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie25/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie25/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie25/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie25/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie25/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie25/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie25/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie25/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie25/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie25/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie25/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie25/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie25/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie25/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie25/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie25/"

REM REM S1GA06
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie26/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie26/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie26/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie26/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie26/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie26/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie26/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie26/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie26/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie26/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie26/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie26/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie26/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie26/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie26/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie26/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie26/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie26/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie26/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie26/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie26/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie26/"

REM REM S2GA06
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie27/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie27/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie27/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie27/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie27/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie27/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie27/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie27/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie27/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie27/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie27/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie27/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie27/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie27/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie27/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie27/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie27/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie27/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie27/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie27/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie27/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie27/"

REM REM S3GA06
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie28/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie28/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie28/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie28/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie28/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie28/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie28/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie28/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie28/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie28/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie28/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie28/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie28/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie28/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie28/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie28/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie28/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie28/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie28/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie28/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie28/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie28/"

REM REM S4GA06
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie29/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie29/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie29/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie29/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie29/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie29/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie29/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie29/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie29/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie29/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie29/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie29/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie29/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie29/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie29/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie29/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie29/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie29/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie29/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie29/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie29/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie29/"

REM REM LNGA06
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie30/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie30/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie30/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie30/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie30/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie30/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie30/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie30/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie30/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie30/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie30/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie30/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie30/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie30/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie30/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie30/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie30/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie30/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie30/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie30/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie30/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie30/"

REM REM S1GA07
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie31/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie31/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie31/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie31/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie31/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie31/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie31/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie31/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie31/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie31/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie31/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie31/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie31/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie31/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie31/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie31/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie31/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie31/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie31/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie31/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie31/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie31/"

REM REM S2GA07
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie32/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie32/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie32/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie32/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie32/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie32/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie32/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie32/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie32/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie32/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie32/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie32/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie32/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie32/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie32/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie32/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie32/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie32/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie32/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie32/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie32/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie32/"

REM REM S3GA07
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie33/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie33/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie33/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie33/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie33/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie33/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie33/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie33/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie33/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie33/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie33/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie33/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie33/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie33/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie33/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie33/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie33/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie33/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie33/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie33/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie33/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie33/"

REM REM S4GA07
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie34/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie34/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie34/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie34/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie34/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie34/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie34/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie34/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie34/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie34/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie34/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie34/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie34/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie34/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie34/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie34/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie34/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie34/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie34/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie34/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie34/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie34/"

REM REM LNGA07
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie35/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie35/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie35/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie35/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie35/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie35/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie35/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie35/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie35/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie35/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie35/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie35/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie35/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie35/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie35/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie35/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie35/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie35/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie35/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie35/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie35/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie35/"

REM REM LNB
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie36/zoom05/5" "E:/LocalData/startanalyse_tiles/tiles/Strategie36/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie36/zoom06/6" "E:/LocalData/startanalyse_tiles/tiles/Strategie36/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie36/zoom07/7" "E:/LocalData/startanalyse_tiles/tiles/Strategie36/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie36/zoom08/8" "E:/LocalData/startanalyse_tiles/tiles/Strategie36/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie36/zoom09/9" "E:/LocalData/startanalyse_tiles/tiles/Strategie36/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie36/zoom10/10" "E:/LocalData/startanalyse_tiles/tiles/Strategie36/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie36/zoom11/11" "E:/LocalData/startanalyse_tiles/tiles/Strategie36/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie36/zoom12/12" "E:/LocalData/startanalyse_tiles/tiles/Strategie36/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie36/zoom13/13" "E:/LocalData/startanalyse_tiles/tiles/Strategie36/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie36/zoom14/14" "E:/LocalData/startanalyse_tiles/tiles/Strategie36/"
REM move /y "E:/LocalData/startanalyse_tiles/tmp_tiles/Strategie36/zoom15/15" "E:/LocalData/startanalyse_tiles/tiles/Strategie36/"