REM ogr2ogr -f MVT ./strategie_1 C:/LocalData/startanalyse_2_0/Strategie1.gpkg -dsco MAX_SIZE=50000000 -dsco MAX_FEATURES=2000000 -dsco MINZOOM=5 -dsco MAXZOOM=18 -dsco COMPRESS=NO -dsco SIMPLIFICATION=0.0 -dsco SIMPLIFICATION_MAX_ZOOM=0.0 -dsco FORMAT=DIRECTORY -dsco CONF=C:/Users/Cicada/prj/SAVI2/data/conf_zoom_strat_1.json
REM ogr2ogr -f MVT ./strategie_2 C:/LocalData/startanalyse_2_0/Strategie2.gpkg -dsco MAX_SIZE=50000000 -dsco MAX_FEATURES=2000000 -dsco MINZOOM=5 -dsco MAXZOOM=18 -dsco COMPRESS=NO -dsco SIMPLIFICATION=0.0 -dsco SIMPLIFICATION_MAX_ZOOM=0.0 -dsco FORMAT=DIRECTORY -dsco CONF=C:/Users/Cicada/prj/SAVI2/data/conf_zoom_strat_2.json
REM ogr2ogr -f MVT ./strategie_3 C:/LocalData/startanalyse_2_0/Strategie3.gpkg -dsco MAX_SIZE=50000000 -dsco MAX_FEATURES=2000000 -dsco MINZOOM=5 -dsco MAXZOOM=18 -dsco COMPRESS=NO -dsco SIMPLIFICATION=0.0 -dsco SIMPLIFICATION_MAX_ZOOM=0.0 -dsco FORMAT=DIRECTORY -dsco CONF=C:/Users/Cicada/prj/SAVI2/data/conf_zoom_strat_3.json
REM ogr2ogr -f MVT ./strategie_4 C:/LocalData/startanalyse_2_0/Strategie4.gpkg -dsco MAX_SIZE=50000000 -dsco MAX_FEATURES=2000000 -dsco MINZOOM=5 -dsco MAXZOOM=18 -dsco COMPRESS=NO -dsco SIMPLIFICATION=0.0 -dsco SIMPLIFICATION_MAX_ZOOM=0.0 -dsco FORMAT=DIRECTORY -dsco CONF=C:/Users/Cicada/prj/SAVI2/data/conf_zoom_strat_4.json
REM ogr2ogr -f MVT ./strategie_5 C:/LocalData/startanalyse_2_0/Strategie5.gpkg -dsco MAX_SIZE=50000000 -dsco MAX_FEATURES=2000000 -dsco MINZOOM=5 -dsco MAXZOOM=18 -dsco COMPRESS=NO -dsco SIMPLIFICATION=0.0 -dsco SIMPLIFICATION_MAX_ZOOM=0.0 -dsco FORMAT=DIRECTORY -dsco CONF=C:/Users/Cicada/prj/SAVI2/data/conf_zoom_strat_5.json
REM ogr2ogr -f MVT ./strategie_6 C:/LocalData/startanalyse_2_0/Strategie6.gpkg -dsco MAX_SIZE=50000000 -dsco MAX_FEATURES=2000000 -dsco MINZOOM=5 -dsco MAXZOOM=18 -dsco COMPRESS=NO -dsco SIMPLIFICATION=0.0 -dsco SIMPLIFICATION_MAX_ZOOM=0.0 -dsco FORMAT=DIRECTORY -dsco CONF=C:/Users/Cicada/prj/SAVI2/data/conf_zoom_strat_6.json
REM ogr2ogr -f MVT ./strategie_7 C:/LocalData/startanalyse_2_0/Strategie7.gpkg -dsco MAX_SIZE=50000000 -dsco MAX_FEATURES=2000000 -dsco MINZOOM=5 -dsco MAXZOOM=18 -dsco COMPRESS=NO -dsco SIMPLIFICATION=0.0 -dsco SIMPLIFICATION_MAX_ZOOM=0.0 -dsco FORMAT=DIRECTORY -dsco CONF=C:/Users/Cicada/prj/SAVI2/data/conf_zoom_strat_7.json
REM ogr2ogr -f MVT ./strategie_8 C:/LocalData/startanalyse_2_0/Strategie8.gpkg -dsco MAX_SIZE=50000000 -dsco MAX_FEATURES=2000000 -dsco MINZOOM=5 -dsco MAXZOOM=18 -dsco COMPRESS=NO -dsco SIMPLIFICATION=0.0 -dsco SIMPLIFICATION_MAX_ZOOM=0.0 -dsco FORMAT=DIRECTORY -dsco CONF=C:/Users/Cicada/prj/SAVI2/data/conf_zoom_strat_8.json

ogr2ogr -f MVT ./strategie_1 C:/LocalData/startanalyse_2_0/Strategie1.gpkg -dsco MAX_SIZE=50000000 -dsco MAX_FEATURES=2000000 -dsco MINZOOM=5 -dsco MAXZOOM=15 -dsco COMPRESS=NO -dsco SIMPLIFICATION=0.0 -dsco SIMPLIFICATION_MAX_ZOOM=0.0 -dsco FORMAT=DIRECTORY -dsco CONF=C:/Users/Cicada/prj/SAVI2/data/conf_zoom_strat_1_t.json
ogr2ogr -f MVT ./strategie_2 C:/LocalData/startanalyse_2_0/Strategie2.gpkg -dsco MAX_SIZE=50000000 -dsco MAX_FEATURES=2000000 -dsco MINZOOM=5 -dsco MAXZOOM=15 -dsco COMPRESS=NO -dsco SIMPLIFICATION=0.0 -dsco SIMPLIFICATION_MAX_ZOOM=0.0 -dsco FORMAT=DIRECTORY -dsco CONF=C:/Users/Cicada/prj/SAVI2/data/conf_zoom_strat_2_t.json
ogr2ogr -f MVT ./strategie_3 C:/LocalData/startanalyse_2_0/Strategie3.gpkg -dsco MAX_SIZE=50000000 -dsco MAX_FEATURES=2000000 -dsco MINZOOM=5 -dsco MAXZOOM=15 -dsco COMPRESS=NO -dsco SIMPLIFICATION=0.0 -dsco SIMPLIFICATION_MAX_ZOOM=0.0 -dsco FORMAT=DIRECTORY -dsco CONF=C:/Users/Cicada/prj/SAVI2/data/conf_zoom_strat_3_t.json
ogr2ogr -f MVT ./strategie_4 C:/LocalData/startanalyse_2_0/Strategie4.gpkg -dsco MAX_SIZE=50000000 -dsco MAX_FEATURES=2000000 -dsco MINZOOM=5 -dsco MAXZOOM=15 -dsco COMPRESS=NO -dsco SIMPLIFICATION=0.0 -dsco SIMPLIFICATION_MAX_ZOOM=0.0 -dsco FORMAT=DIRECTORY -dsco CONF=C:/Users/Cicada/prj/SAVI2/data/conf_zoom_strat_4_t.json
ogr2ogr -f MVT ./strategie_5 C:/LocalData/startanalyse_2_0/Strategie5.gpkg -dsco MAX_SIZE=50000000 -dsco MAX_FEATURES=2000000 -dsco MINZOOM=5 -dsco MAXZOOM=15 -dsco COMPRESS=NO -dsco SIMPLIFICATION=0.0 -dsco SIMPLIFICATION_MAX_ZOOM=0.0 -dsco FORMAT=DIRECTORY -dsco CONF=C:/Users/Cicada/prj/SAVI2/data/conf_zoom_strat_5_t.json
ogr2ogr -f MVT ./strategie_6 C:/LocalData/startanalyse_2_0/Strategie6.gpkg -dsco MAX_SIZE=50000000 -dsco MAX_FEATURES=2000000 -dsco MINZOOM=5 -dsco MAXZOOM=15 -dsco COMPRESS=NO -dsco SIMPLIFICATION=0.0 -dsco SIMPLIFICATION_MAX_ZOOM=0.0 -dsco FORMAT=DIRECTORY -dsco CONF=C:/Users/Cicada/prj/SAVI2/data/conf_zoom_strat_6_t.json
ogr2ogr -f MVT ./strategie_7 C:/LocalData/startanalyse_2_0/Strategie7.gpkg -dsco MAX_SIZE=50000000 -dsco MAX_FEATURES=2000000 -dsco MINZOOM=5 -dsco MAXZOOM=15 -dsco COMPRESS=NO -dsco SIMPLIFICATION=0.0 -dsco SIMPLIFICATION_MAX_ZOOM=0.0 -dsco FORMAT=DIRECTORY -dsco CONF=C:/Users/Cicada/prj/SAVI2/data/conf_zoom_strat_7_t.json
ogr2ogr -f MVT ./strategie_8 C:/LocalData/startanalyse_2_0/Strategie8.gpkg -dsco MAX_SIZE=50000000 -dsco MAX_FEATURES=2000000 -dsco MINZOOM=5 -dsco MAXZOOM=15 -dsco COMPRESS=NO -dsco SIMPLIFICATION=0.0 -dsco SIMPLIFICATION_MAX_ZOOM=0.0 -dsco FORMAT=DIRECTORY -dsco CONF=C:/Users/Cicada/prj/SAVI2/data/conf_zoom_strat_8_t.json